// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9yP00Yz9j5pqCI3JpfWMHxHSPfqA5RZg',
    appId: '1:672431700340:web:11478c970e35454df9d421',
    messagingSenderId: '672431700340',
    projectId: 'alexgames-app-cultuar',
    authDomain: 'alexgames-app-cultuar.firebaseapp.com',
    storageBucket: 'alexgames-app-cultuar.firebasestorage.app',
    measurementId: 'G-MM1J3GMPX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-2Fbb6ikmsCQomjI5OELCAIMyo-hlty4',
    appId: '1:672431700340:android:f6ef4b6f76c23652f9d421',
    messagingSenderId: '672431700340',
    projectId: 'alexgames-app-cultuar',
    storageBucket: 'alexgames-app-cultuar.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9yP00Yz9j5pqCI3JpfWMHxHSPfqA5RZg',
    appId: '1:672431700340:web:03c1b95b1c9e641ef9d421',
    messagingSenderId: '672431700340',
    projectId: 'alexgames-app-cultuar',
    authDomain: 'alexgames-app-cultuar.firebaseapp.com',
    storageBucket: 'alexgames-app-cultuar.firebasestorage.app',
    measurementId: 'G-9CWHCHF3EJ',
  );
}
